apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orders-db
  namespace: ecommerce
spec:
  serviceName: orders-db
  replicas: 1
  selector:
    matchLabels:
      app: orders-db
  template:
    metadata:
      labels:
        app: orders-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: ordersdb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: postgres-password
          volumeMounts:
            - name: orders-db-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: orders-db-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: orders-db
  namespace: ecommerce
spec:
  selector:
    app: orders-db
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
