apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret }}
  postgres-password: {{ .Values.secrets.postgresPassword }}
